main: jp\mazaicrafty\pmmp\main
name: TestPlugin
author: MazaiCrafty
version: POSTWORLD
api:
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
description: "Test Plugin"
website: https://github.com/MazaiCrafty