main: jp\mazaicrafty\pmmp\main
name: TestPlugin
author: MazaiCrafty
version: "0.1.2"
load: POSTWORLD
api:
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
description: "Test Plugin"
website: https://github.com/MazaiCrafty
commands:
  test:
    description: ""
    permission: test.command
  pertest:
    description: ""
    permission: pertest.command
permissions:
  test.command:
    default: true
  pertest.command:
    default: op